name: OctoDNS
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Tested versions based on dates in https://devguide.python.org/devcycle/#end-of-life-branches, 
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install virtualenv
      - name: CI Build
        run: |
          ./script/cibuild
